### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by dazld** [jsantell/node-json-front-matter#9]
The package looks pretty stable, how about updating it to `v1.0.0` .. ? 

I've put together a browserify transform (https://github.com/dazld/frontmatterify) that uses both this and a yaml front matter parser, and would be great to be able to reference a 'stable' release instead of the 0.x versions on npm! 

Side question - what extensions do people normally use for front matter files? Is there a standardised way of referring to them..? I'm using `.json.fm` and `.yaml.fm`\- for an example.

What do you think..?

**Comment by jsantell** [comment]
You're right -- this has been stable long enough. Updated to 1.0.0 and published to npm, thanks for the ping :)

Regarding file extension naming, I'm not sure on that, as personally I've been using them within markdown files (so just `.md`), guess it depends on what the `body` of the file is!

**Comment by dazld** [comment]
great, I'll update my packages too. the body content is important, you're right - maybe the jekyll people have some convention, but guess they only use yaml. Anyway, not a biggie - maybe I'll just update the transform to let people choose what they want, instead of trying to magically infer it from extension. thanks!
